#importar base de python
FROM python:3.12-slim

#Crear en el contenedor - Carpeta de trabajo
WORKDIR /app

#Copiar los requerimientos al contenedor
COPY requirements.txt .

#Instalar las dependencias de FASTAPI
RUN pip install --no-cache-dir -r requirements.txt

#Copiar el codigo del servidor
COPY  . .

#Exponer el puerto de trabajo
EXPOSE 5000

#Comando a ejecutar para levantar el servidor
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
